[project]
name = "21cm-wrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "21cmfast>=3.4.0",
    "numpy>=1.26.4",
]
